spring:
  application:
    name: jobsearchermcpserver
  ai:
    mcp:
      server:
        name: jobsearchermcpserver
        version: 0.1.1
        protocol: streamable
        stdio: false
        type: sync
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/jobsearchermcpserver.log